---
title: "THE PHANTOM OF THE OPERA lyrics term frequency"
author: "claire"
date: "2018年7月21日"
output: html_document
---

```{r}
library(tm)
library(tmcn)
library(factoextra)
library(Matrix)
library(NLP)
library(wordcloud)

music.corpus <- Corpus( DirSource("./musical") )
#DirSource是Directory Source顧名思義就是指定一個資料夾作為資料來源所以參數是要放一個資料夾的路徑
#開始清理資料

toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)

music.corpus <- tm_map(music.corpus, toSpace, "you")
music.corpus <- tm_map(music.corpus, toSpace, "and")
music.corpus <- tm_map(music.corpus, toSpace, "her")
music.corpus <- tm_map(music.corpus, toSpace, "all")
music.corpus <- tm_map(music.corpus, toSpace, "that")
music.corpus <- tm_map(music.corpus, toSpace, "let")
music.corpus <- tm_map(music.corpus, toSpace, "with")
music.corpus <- tm_map(music.corpus, toSpace, "for")
music.corpus <- tm_map(music.corpus, toSpace, "say")
music.corpus <- tm_map(music.corpus, toSpace, "the")
music.corpus <- tm_map(music.corpus, toSpace, "fat")
music.corpus <- tm_map(music.corpus, toSpace, "this")
music.corpus <- tm_map(music.corpus, toSpace, "each")
music.corpus <- tm_map(music.corpus, toSpace, "what")
music.corpus <- tm_map(music.corpus, toSpace, "were")
#清理不需要的文字完畢


#將標點消除，轉小寫，再轉成tdm表格
music.corpus <- tm_map(music.corpus, removePunctuation)
music.corpus<- tm_map(music.corpus, content_transformer(tolower))
music.tdm <- TermDocumentMatrix(music.corpus, control = list())
inspect(music.tdm)
#檢查成果
```

```{r}
#TDM 轉成 TF-IDF
#nnzero returns the number of non-zero values of a numeric-like R object, and in particular an object x inheriting from class

docs.tf <- apply(as.matrix(music.tdm), 2, function(word) { word/sum(word) })
idf.function <- function(word_doc) { log2( (length(word_doc)+1) / nnzero(word_doc) ) }
docs.idf <- apply(as.matrix(music.tdm), 1, idf.function)
docs.tfidf <- docs.tf * docs.idf
#察看結果
head(docs.tfidf)
```
```{r}
#查詢字頻
query.tfidf <- function(q){
  q.position <- which(rownames(docs.tfidf) %in% q)
  q.tfidf <- docs.tfidf[q.position, ]
  return (q.tfidf)
}
query.tfidf(c("angel","christine","phantom","music"))
```

```{r}
#計算個詞彙的詞頻總和
#先按照頻率高低排列
#把單詞-詞頻對應存入 data frame
#劃出文字雲
f <- sort(rowSums(docs.tfidf), decreasing = T)
docs.df <- data.frame(
  word = names(f),
  freq = f
)
#如果出現了裝不下字元的警告，可以調整scale和max.words
wordcloud(docs.df$word, docs.df$freq, scale = c(4.5, 0.2),max.words = 100, colors=brewer.pal(8, "Dark2"))
```


```{r}
docs.pca <- prcomp(docs.tfidf, scale = T)

fviz_eig(docs.pca)
```

```{r}
fviz_pca_ind(docs.pca, geom.ind = c("point"), col.ind = "cos2")
```

```{r}
fviz_pca_var(docs.pca, col.var = "contrib")
```

```{r}
fviz_pca_biplot(docs.pca, geom.ind = "point")
```

```{r}
#k-means
docs.eig <- get_eig(docs.pca)
docs.var <- get_pca_var(docs.pca)
docs.ind <- get_pca_ind(docs.pca)

ind.coord2 <- docs.ind$coord[, 1:2]
wss <- c()
for (i in 1:10) { wss[i] <- kmeans(ind.coord2, i)$tot.withinss }
plot(wss, type = "b")

km <- kmeans(ind.coord2, 3)
plot(ind.coord2, col = km$cluster)
points(km$centers, col = 1:3, pch = 8, cex = 2)
```